### ISSUE TITLE
Docker permission error

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/javascript-test-runner#43]
If I try to run the test runner in Docker using `./run-in-docker.sh leap ../javascript/exercises/practice/leap  ../javascript/exercises/practice/leap` (which assumes there is a sibling `javascript` repo checked out), I get an error:

```
Using reporter : /opt/test-runner/dist/reporter.js
Using test-root: /solution/
Using base-root: /opt/test-runner
Using setup-env: /opt/test-runner/dist/jest/setup.js
Using /solution/.meta/config.json as base configuration
Enabling tests in /solution/leap.spec.js
sed: couldn't open temporary file /solution/sedXo2Ajt: Permission denied
sed: couldn't open temporary file /solution/sedaMcAZw: Permission denied
sed: couldn't open temporary file /solution/sedNuro8w: Permission denied
```

This transformation is done in `prepare.sh`. If I run `ls -al` in `prepare.sh` to check the permissions, I get:

```
drwxr-xr-x 4 node node 4096 May 12 11:45 .
drwxr-xr-x 1 root root 4096 May 12 11:48 ..
drwxr-xr-x 2 node node 4096 May 12 11:45 .docs
-rw-r--r-- 1 node node  318 May 12 11:45 .eslintrc
drwxr-xr-x 2 node node 4096 May 12 11:45 .meta
-rw-r--r-- 1 node node   12 May 12 11:45 .npmrc
-rw-r--r-- 1 node node 1065 May 12 11:45 LICENSE
-rw-r--r-- 1 node node  252 May 12 11:45 babel.config.js
-rw-r--r-- 1 node node  248 May 12 11:45 leap.js
-rw-r--r-- 1 node node 1107 May 12 11:45 leap.spec.js
-rw-r--r-- 1 node node  816 May 12 11:45 package.json
```

The Dockerfile specifies that the image is run as user `appuser`, which then doesn't have the required permissions.

**Comment by SleeplessByte** [comment]
I can't get `run-in-docker` to work properly. I can't seem to `docker login` without `sudo` which means that I can't run the entire thing without `sudo` because it now requires login to build the image. This all means that I can't test this out on my own machines, therefore I can't fix this. 

I can't work around this issue either, so someone else should pick it up or we should leave it broken. I don't know enough of docker to "guess" the fix.

My latest attempts to guess a fix are on master. If they don't work then 🤷🏽. I'm not interested in spending more time to get it resolved either, it just feels like wasted energy and effort on something I neither have fun nor interest in doing, just because we decided to use some arbitrary "container" system which we might not even half in 6 months.

Note that the proposed command:

```shell
./run-in-docker.sh leap ../javascript/exercises/practice/leap ../javascript/exercises/practice/leap
```

...will NEVER work, because it's making the input dir (what's mapped to `/solution`) the same as the output dir (what's mapped to `/output`) and that's always going to have the same user (root??) and thus never be writable.

Maybe we should just delete the appuser user and not care about the security.

```text
sudo ./run-in-docker.sh leap ../javascript/exercises/practice/leap ../javascript/exercises/practice/leap

[sudo] password for derk-jan: 

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
[+] Building 138.4s (11/11) FINISHED                                         

/solution/ matches /output/. Not copying anything.
No configuration given. Falling back to leap.spec.js
Can't find /output/leap.spec.js
No tests found, exiting with code 0
Test Suites: 0 total
Tests:       0 total
Snapshots:   0 total
Time:        0.001s
Error: EACCES: permission denied, open '/output/results.json'
```

**Comment by iHiD** [comment]
To be clear, this is an issue with the run-in-docker file, right, now the actual test runner?

**Comment by junedev** [comment]
Another question to narrow it down. Does the  command in run-in-docker.sh work fine in other tracks? Maybe @ErikSchierboom knows.

**Comment by BethanyG** [comment]
I may be entirely wrong.  But I **think** I've seen this problem with Python's test runner.  I switched to running the `run.sh` script instead, and assumed that since it was running on `lol`, it was ok.  But now I am curious.  I will fire up the docker version and test to see if I get the same error invoking `run-in-docker.sh`.

**Comment by neenjaw** [comment]
I'll take a peek at this. I have 3 test runners working with this script that was added. (php, crystal, elixir)

**Comment by SleeplessByte** [comment]
Thank you all for helping out because I'm really out of my dept here.

**Comment by iHiD** [comment]
I suspect changing https://github.com/exercism/javascript-test-runner/blob/main/run-in-docker.sh#L32-L33 from `bind` to `volume` might work. In production we use the `-v` flag (see https://github.com/exercism/tooling-invoker/blob/d808db03a77476c0fa24cb7030e783edf395fe57/lib/tooling_invoker/exec_docker.rb#L158)

**Comment by neenjaw** [comment]
This issue is the `bind` mounting, but I don't think changing it to `volume` won't fix the issue.  The `bind` type means that the host file system is the mounted along with its permissions.  A `volume` mount is managed by docker engine.  The `-v` is an alternate shorthand form of the `--mount` option, functionally they are equivalent. 

Anyway, I think in the environment that @ErikSchierboom is using, the folder doesn't give permissions to the `appuser` to write to the directory.  The solution is to give the `appuser` owner/group permissions on the host fs to be able to write to it.  I'm not sure exactly what that might entail to do that, but it seems to be done in production, which is why it works there. I also am able to run this same script successfully in the php and elixir test runners which also use unprivileged users.

:)

**Comment by SleeplessByte** [comment]
So we should close this as "wontfix"?

**Comment by ErikSchierboom** [comment]
I'll take a look at this next week. Thanks everyone for chipping in.

**Comment by ErikSchierboom** [comment]
I can't get it working locally, but as it's working fine on exercism.lol, I'll close.
